#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>
#include <limits.h>
#include <pthread.h>
#include <sys/resource.h>
#include <errno.h>
#include <ulimit.h>
#include <signal.h>
#include <time.h>
#include <math.h>
#include "d_types.h"
#include "process_request.h"
#include "disk_scheduler.h"